[package]
name = "async_RESTful_api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.39", features = ["serde"] }
dotenvy = "0.15.7"
fern = "0.7.1"
log = "0.4.22"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
